version: "3.7"

services:
  db_parser:
    container_name: db_parser
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: unless-stopped
    volumes:
      - db-parser-data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - ${DB_PORT}:5432
    networks:
      - project_parser


volumes:
  db-parser-data:


networks:
  project_parser:
    external: true
