"""create urls table

Revision ID: 73c04da08a49
Revises: 
Create Date: 2023-02-01 22:22:34.430565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "73c04da08a49"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.TEXT(), nullable=False),
        sa.Column("final_url", sa.TEXT(), nullable=True),
        sa.Column("status_code", sa.INTEGER(), nullable=True),
        sa.Column("page_title", sa.VARCHAR(), nullable=True),
        sa.Column("domain_name", sa.VARCHAR(), nullable=False),
        sa.Column("parse_date", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("visit_date", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_urls_domain_name"), "urls", ["domain_name"], unique=False)
    op.create_index(op.f("ix_urls_url"), "urls", ["url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urls_url"), table_name="urls")
    op.drop_index(op.f("ix_urls_domain_name"), table_name="urls")
    op.drop_table("urls")
    # ### end Alembic commands ###
